version: 2.1

executors:
  dotnet-default:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest

jobs:
  build:
    executor: dotnet-default
    steps:
      - checkout

      - run:
          name: Install Additional Dependencies (Optional)
          command: |
            apt-get update
            apt-get install -y zip unzip

      - run:
          name: Make build script executable
          command: |
            chmod +x auto-build.sh

      - run:
          name: Execute auto-build script
          command: |
            ./auto-build.sh

      - persist_to_workspace:
          root: bin
          paths:
            - ./bin

  release:
    executor: dotnet-default
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Prepare release
          command: |
            echo Creating release archive
            mkdir release
            zip -r ./release/jotter-release.zip ./workspace/bin/x64/Release/net8.0-windows/publishprod/*
      - store_artifacts:
          path: ./release/jotter-release.zip
          destination: jotter-release.zip

workflows:
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
