# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      
      - run:
          name: Install Additional Dependencies (Optional)
          command: |
            tree /f

      - run:
          name: Set up build environment
          command: |
            echo Setting up environment variables
            set IS_DEBUG=false
            set VERBOSE_LEVEL=normal

      - run:
          name: Execute auto-build script
          command: |
            ./auto-build.cmd
            tree /f

      - persist_to_workspace:
          root: bin
          paths:
            - ./bin

  release:
    executor: win/default
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Prepare release
          command: |
            echo Creating release archive
            mkdir release
            zip -r ./release/jotter-release.zip ./workspace/bin/x64/Release/net8.0-windows/publishprod/*
      - store_artifacts:
          path: ./release/jotter-release.zip
          destination: jotter-release.zip

workflows:
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
