# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
#
version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor: win/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:q7mwwYGg5K0Vf6IYVuNanJlLdX3DjFEdfyMyIOOABWU"
      - checkout
      
      - run:
          name: Install Additional Dependencies (GitHub CLI and zip)
          command: |
            # Install Chocolatey package manager and dependencies
            choco install gh zip -y 
            # Verify installations
            where gh 
            where zip

      - run:
          name: Set up build environment
          command: |
            echo Setting up environment variables
            set IS_DEBUG=false
            set VERBOSE_LEVEL=normal

      - run:
          name: Execute auto-build script
          command: |
            ./auto-build.cmd

      - run:
          name: Commit and Push Updated Version
          command: |
            git config --global user.name "SorryNoFocus"
            git config --global user.email "thechriswinters@gmail.com"
            echo "Committing updated versioninfo.txt to the repository"
            set /p TAG_NAME=<build\versioninfo.txt
            echo "Release tag read: v%TAG_NAME%"            
            git add build\versioninfo.txt
            git status
            git commit -am "Update versioninfo.txt to reflect release version [skip ci]"
            git push origin HEAD

      - persist_to_workspace:
          root: C:\Users\circleci\project\
          paths:
            - .git
            - bin\x64\Release\net8.0-windows\publishprod
            - build\versioninfo.txt

  release:
    executor: win/default
    steps:
      - attach_workspace:
          at: C:\workspace

      - run:
          name: Install Additional Dependencies (GitHub CLI and zip)
          command: |
            choco install gh zip -y 
            where zip

      - run:
          name: Prepare release
          command: |
            echo Creating release archive
            mkdir C:\workspace\release\
            zip -r C:\workspace\release\jotter-release.zip C:\workspace\bin\x64\Release\net8.0-windows\publishprod\*.exe

      - run:
          name: Read Version Information
          command: |
            # Read the version from the file 
            $versionFilePath = ".\versioninfo.txt" 
            $TAG_NAME = Get-Content -Path $versionFilePath -Raw 
            # Output the release tag 
            Write-Output "Detected release from versioninfo: v$TAG_NAME"

      - store_artifacts:
          path: C:\workspace\release\jotter-release.zip
          destination: jotter-release.zip

      - run:
          name: Create GitHub Release
          command: |
            # Create the release name 
            $RELEASE_NAME = "Release v$TAG_NAME" 
            Write-Output "Creating release $RELEASE_NAME"

            # Ensure Git context is valid
            git config --global user.name "SorryNoFocus"
            git config --global user.email "thechriswinters@gmail.com"

            # Create the GitHub release
            gh release create "v%TAG_NAME%" C:\workspace\release\jotter-release.zip `
              --title "Release v%TAG_NAME%" `
              --notes "Automated release via CircleCI"


workflows:
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
