# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  dotnet-default:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0-nanoserver-ltsc2022

jobs:
  build:
    executor: dotnet-default
    steps:
      - checkout
      
      - run:
          name: Install Additional Dependencies (Optional)
          command: |
            apt-get update
            apt-get install -y zip unzip
            tree /f

      - run:
          name: Set up build environment
          command: |
            echo Setting up environment variables
            export IS_DEBUG=false
            export VERBOSE_LEVEL=normal

      - run:
          name: Execute auto-build script
          command: |
            chmod +x auto-build.cmd
            call ./auto-build.cmd

      - persist_to_workspace:
          root: bin
          paths:
            - ./bin

  release:
    executor: dotnet-default
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Prepare release
          command: |
            echo Creating release archive
            mkdir release
            zip -r ./release/jotter-release.zip ./workspace/bin/x64/Release/net8.0-windows/publishprod/*
      - store_artifacts:
          path: ./release/jotter-release.zip
          destination: jotter-release.zip

workflows:
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
