# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      
      - run:
          name: Install Additional Dependencies (github CLI)
          command: |
            # Install Chocolatey package manager
            #powershell -NoProfile -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" 
            # Install GitHub CLI using Chocolatey 
            choco install gh zip -y 
            # Verify installation 
            where gh 
            where zip
            #gh --version

      - run:
          name: Set up build environment
          command: |
            echo Setting up environment variables
            set IS_DEBUG=false
            set VERBOSE_LEVEL=normal

      - run:
          name: Execute auto-build script
          command: |
            ./auto-build.cmd
            tree /f


  release:
    executor: win/default
    steps:
      - attach_workspace:
          at: ./workspace
      - run:
          name: Prepare release
          command: |
            echo Creating release archive
            mkdir release
            zip -r ./release/jotter-release.zip ./workspace/bin/x64/Release/net8.0-windows/publishprod/*
      - run:
          name: Create GitHub Release
          command: |
            TAG_NAME=v$(date +"%Y%m%d%H%M%S") # Example tag name based on timestamp
            RELEASE_NAME="Release $TAG_NAME"
            echo "Creating release $RELEASE_NAME"

            # Create the GitHub release
            gh release create "$TAG_NAME" ./release/jotter-release.zip \
              --title "$RELEASE_NAME" \
              --notes "Automated release via CircleCI"
      - store_artifacts:
          path: ./release/jotter-release.zip
          destination: jotter-release.zip

workflows:
  build-and-release:
    jobs:
      - build
      - release:
          requires:
            - build
